<?php


namespace app\admin\controller;

use think\Db;

use think\Controller;

/**
 * 登录中间件
 * Class Baseadmin
 * User: Ehua
 * Alter: 2022/2/11 9:53
 * @package app\admin\controller
 */
class Baseadmin extends Common
{
    public $prefix;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if (!session('server')) {
            return $this->redirect($this->admPath . '/login/login');
        }


        $this->prefix = config('database.prefix');
    }
}